GymManagment/Pages/AboutUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymManagment.Pages
{
    public class AboutUsModel : PageModel
    {
		private readonly ICMSRepository _cmsRepository;

		public AboutUsModel(ICMSRepository cmsRepository)
		{
			_cmsRepository = cmsRepository;
		}

		public CMSContentViewModel AboutUs { get; set; }

		public async Task OnGetAsync()
        {
			AboutUs = (await _cmsRepository.GetCMSContent("AboutUs")).ToList().FirstOrDefault();
		}
    }
}

GymManagment/Pages/Admin/AboutUs.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class AboutUsModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public AboutUsModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync()
        {

            var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.CMSKey == "AboutUs");
            Master = _mapper.Map<CMSContentViewPostModel>(data);
            if (data != null && data.Media != null)
            {
                ImageURL = data.Media.FileName;
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("../Home");
        }
    }
}

GymManagment/Pages/Admin/Banner.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class BannerModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public BannerModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.Id == id);
                Master = _mapper.Map<CMSContentViewPostModel>(data);
                if (data.Media != null)
                {
                    ImageURL = data.Media.FileName;
                }
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "Banners");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("BannerList");
        }
    }
}

GymManagment/Pages/Admin/BannerList.cshtml.cs
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class BannerListModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public BannerListModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<CMSContent> Items { get; set; }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public bool DeleteConfirmed = false;

        public Dictionary<string, string> CMSValue = new Dictionary<string, string>()
        {
            { "IndexBanner","Index" },
            { "ContactUsBanner","Contact Us" },
            { "ServiceBanner","Service" },
            { "HRMBanner","HRM Service" },
            { "MaritimeBanner","Maritime Service" },
            { "TechnicalBanner","Technical Service" },
            { "ConsultancyBanner","Consultancy Service" },
            { "OilBanner","Oil Spill Response Service" },
            { "DredgingBanner","Dredging Services" },
            { "ProjectBanner","Projects" },
            { "AboutUsMainBanner","About Us Main" },
            { "OpeningBanner","Current Openings" }
        };

        public async Task OnGetAsync()
        {
            Items = await _context.CMSContents.Where(i => i.CMSKey == "IndexBanner" ||
                                                     i.CMSKey == "ContactUsBanner" ||
                                                     i.CMSKey == "ServiceBanner" ||
                                                     i.CMSKey == "HRMBanner" ||
                                                     i.CMSKey == "MaritimeBanner" ||
                                                     i.CMSKey == "TechnicalBanner" ||
                                                     i.CMSKey == "ConsultancyBanner" ||
                                                     i.CMSKey == "OilBanner" ||
                                                     i.CMSKey == "DredgingBanner" ||
                                                     i.CMSKey == "ProjectBanner" ||
                                                     i.CMSKey == "AboutUsMainBanner" ||
                                                     i.CMSKey == "OpeningBanner").ToListAsync();
            DeleteConfirmed = false;
        }

        public async Task<IActionResult> OnPostDeleteAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Where(x => x.Id == id).FirstOrDefaultAsync();
                if (data != null)
                {
                    _context.CMSContents.Remove(data);
                    _context.SaveChanges();
                }
            }
            Items = await _context.CMSContents.Where(i => i.CMSKey == "IndexBanner" ||
                                                     i.CMSKey == "ContactUsBanner" ||
                                                     i.CMSKey == "HRMBanner" ||
                                                     i.CMSKey == "ServiceBanner" ||
                                                     i.CMSKey == "MaritimeBanner" ||
                                                     i.CMSKey == "TechnicalBanner" ||
                                                     i.CMSKey == "ConsultancyBanner" ||
                                                     i.CMSKey == "OilBanner" ||
                                                     i.CMSKey == "DredgingBanner" ||
                                                     i.CMSKey == "ProjectBanner" ||
                                                     i.CMSKey == "AboutUsMainBanner" ||
                                                     i.CMSKey == "OpeningBanner").ToListAsync();
            DeleteConfirmed = true;
            return Page();
        }
    }
}

GymManagment/Pages/Admin/Blog.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class BlogModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public BlogModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.Id == id);
                Master = _mapper.Map<CMSContentViewPostModel>(data);
                if (data.Media != null)
                {
                    ImageURL = data.Media.FileName;
                }
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "Blogs");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            Master.Text2 = (Master.Text2.Replace(" ", "-")).ToLower();

            var blogdata = _context.CMSContents.Where(i => i.Text2 == Master.Text2).FirstOrDefault();
            if (blogdata != null)
            {
                int i = 1;
                while (true)
                {
                    var blogdata1 = _context.CMSContents.Where(b => b.Text2 == Master.Text2 + i).FirstOrDefault();
                    if (blogdata1 == null)
                    {
                        Master.Text2 = Master.Text2 + i;
                        break;
                    }
                    i++;
                }
            }

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("BlogList");
        }
    }
}

GymManagment/Pages/Admin/BlogList.cshtml.cs
using GymManagment.Core;
using GymManagment.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class BlogListModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public BlogListModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<CMSContent> Items { get; set; }

        public bool DeleteConfirmed = false;

        public async Task OnGetAsync()
        {
            Items = await _context.CMSContents.Where(i => i.CMSKey == "Blog").ToListAsync();
            DeleteConfirmed = false;
        }

        public async Task<IActionResult> OnPostDeleteAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Where(x => x.Id == id).FirstOrDefaultAsync();
                if (data != null)
                {
                    _context.CMSContents.Remove(data);
                    _context.SaveChanges();
                }
            }
            Items = await _context.CMSContents.Where(i => i.CMSKey == "Blog").ToListAsync();
            DeleteConfirmed = true;
            return Page();
        }
    }
}

GymManagment/Pages/Admin/Client.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class ClientModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public ClientModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.Id == id);
                Master = _mapper.Map<CMSContentViewPostModel>(data);
                if (data.Media != null)
                {
                    ImageURL = data.Media.FileName;
                }
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "Client");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("ClientList");
        }
    }
}

GymManagment/Pages/Admin/EnquiryList.cshtml.cs
using GymManagment.Core;
using GymManagment.Core.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class EnquiryListModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EnquiryListModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<Enquiry> Items { get; set; }

        public async Task OnGetAsync()
        {
            Items = await _context.Enquiries.OrderByDescending(x => x.CreatedOn).ToListAsync();
        }
    }
}

GymManagment/Pages/Admin/AboutUs.cshtml
@page
@model GymManagment.Pages.Admin.AboutUsModel
@{
    Layout = "_AdminLayout";
}
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>About Us</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>

                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form form method="post" enctype="multipart/form-data" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        <input type="hidden" asp-for="Master.Id" />
                        <input type="hidden" asp-for="Master.MediaId" />
                        <input type="hidden" asp-for="Master.IsActive" value="true" />
                        <input type="hidden" asp-for="Master.CMSKey" value="AboutUs" />
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="Master.Text1">
                                Index Page About Us Content<span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 ">
                                <textarea asp-for="Master.Text1" required="required" class="form-control " rows="3"></textarea>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="Master.Text2">
                                About Us Page Content<span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 ">
                                <textarea asp-for="Master.Text2" required="required" class="form-control " rows="3"></textarea>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="Master.Text3">
                                Video URL <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 ">
                                <input type="text" asp-for="Master.Text3" required="required" class="form-control ">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="Master.Image">
                                Image<span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 ">
                                <input type="file" onchange="readURL(this,'img_here')" class="form-control-file" asp-for="Master.Image">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                            </label>
                            <div class="col-md-6 col-sm-6 ">
                                <img id="img_here" src="@Model.ImageURL" alt="Image" class="form-control" style="height: 125px;width: auto;" />
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="item form-group">
                            <div class="col-md-6 col-sm-6 offset-md-3">
                                <input type="button" value="Cancel" class="btn btn-warning" id="btnCancel" />
                                <input type="submit" asp-page-handler="Save" value="Save" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste",
            "textcolor colorpicker"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor"

    });

    $(window).bind("load", function () {
        $(".tox-statusbar").hide();
    });
</script>
@section Scripts {
    <script>
        $('#btnCancel').click(function () {
            window.location.href = '/Admin/AboutUs';
            return false;
        });
    </script>
}

GymManagment/Pages/Admin/BannerList.cshtml
@page
@model GymManagment.Pages.Admin.BannerListModel
@{
    ViewData["Title"] = "Banner's List";
    Layout = "_AdminLayout";
}
<!-- Datatables -->
<link href="~/admin_theme/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="~/admin_theme/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
<link href="~/admin_theme/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
<link href="~/admin_theme/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
<link href="~/admin_theme/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
<div class="">
    <input type="hidden" id="delconfirm" asp-for="DeleteConfirmed" />
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Banner's List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <p class="header-create-new">
                        <input type="button" class="btn btn-primary" value="Create New" id="btnNew">
                    </p>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered" role="grid" aria-describedby="datatable-buttons_info">
                            <thead>
                                <tr>
                                    <th style="width: 25px;"></th>
                                    <th>
                                        Page
                                    </th>
                                    <th>
                                        Header Text
                                    </th>
                                    <th>
                                        Description Text
                                    </th>
                                    <th>
                                        Is Active
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td class="tdpadding">
                                            <a asp-page="Banner" asp-route-id="@item.Id"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                            <form asp-page-handler="delete" asp-route-id="@item.Id" method="post" onclick="return confirm('Are you sure you want to delete this?')">
                                                <button class="remove"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                            </form>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => Model.CMSValue[item.CMSKey])
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Text1)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Text2)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IsActive)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <!-- Datatables -->
    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>
    <script>
        $('#btnNew').click(function () {
            window.location.href = '/Admin/Banner';
            return false;
        });
    </script>
}