GymManagment/Pages/AboutUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymManagment.Pages
{
    public class AboutUsModel : PageModel
    {
		private readonly ICMSRepository _cmsRepository;

		public AboutUsModel(ICMSRepository cmsRepository)
		{
			_cmsRepository = cmsRepository;
		}

		public CMSContentViewModel AboutUs { get; set; }

		public async Task OnGetAsync()
        {
			AboutUs = (await _cmsRepository.GetCMSContent("AboutUs")).ToList().FirstOrDefault();
		}
    }
}

GymManagment/Pages/Admin/AboutUs.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class AboutUsModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public AboutUsModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync()
        {

            var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.CMSKey == "AboutUs");
            Master = _mapper.Map<CMSContentViewPostModel>(data);
            if (data != null && data.Media != null)
            {
                ImageURL = data.Media.FileName;
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("../Home");
        }
    }
}

GymManagment/Pages/Admin/Blog.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class BlogModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public BlogModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.Id == id);
                Master = _mapper.Map<CMSContentViewPostModel>(data);
                if (data.Media != null)
                {
                    ImageURL = data.Media.FileName;
                }
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "Blogs");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            Master.Text2 = (Master.Text2.Replace(" ", "-")).ToLower();

            var blogdata = _context.CMSContents.Where(i => i.Text2 == Master.Text2).FirstOrDefault();
            if (blogdata != null)
            {
                int i = 1;
                while (true)
                {
                    var blogdata1 = _context.CMSContents.Where(b => b.Text2 == Master.Text2 + i).FirstOrDefault();
                    if (blogdata1 == null)
                    {
                        Master.Text2 = Master.Text2 + i;
                        break;
                    }
                    i++;
                }
            }

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("BlogList");
        }
    }
}

GymManagment/Pages/Admin/News.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class NewsModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public NewsModel(ApplicationDbContext context,
            IHttpContextAccessor httpContextAccessor,
            IMediaRepository mediaRepository,
            IMapper mapper,
            IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public CMSContentViewPostModel Master { get; set; }

        public string ImageURL { get; set; }

        public async Task OnGetAsync(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.Id == id);
                Master = _mapper.Map<CMSContentViewPostModel>(data);
                if (data.Media != null)
                {
                    ImageURL = data.Media.FileName;
                }
            }
        }


        public async Task<IActionResult> OnPostSaveAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }

            #region Save Media 
            if (Master.Image != null)
            {
                var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "News");

                if (mediaResult.IsSuccess)
                {
                    Master.MediaId = mediaResult.MediaID;
                }

            }
            #endregion

            Master.Text2 = (Master.Text2.Replace(" ", "-")).ToLower();

            var blogdata = _context.CMSContents.Where(i => i.Text2 == Master.Text2).FirstOrDefault();
            if (blogdata != null)
            {
                int i = 1;
                while (true)
                {
                    var blogdata1 = _context.CMSContents.Where(b => b.Text2 == Master.Text2 + i).FirstOrDefault();
                    if (blogdata1 == null)
                    {
                        Master.Text2 = Master.Text2 + i;
                        break;
                    }
                    i++;
                }
            }

            var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
            if (string.IsNullOrEmpty(Master.Id))
            {
                _context.CMSContents.Add(data);
            }
            else
            {
                _context.Attach(data).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();

            return Redirect("NewsList");
        }
    }
}

GymManagment/Pages/Admin/Settings.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.Admin
{
    public class SettingsModel : BasePageModel
    {
        private readonly IMediaRepository _mediaRepository;
        private readonly IMapper _mapper;

        public SettingsModel(ApplicationDbContext context,
             IHttpContextAccessor httpContextAccessor,
             IMediaRepository mediaRepository,
             IMapper mapper,
             IHostingEnvironment env) : base(context, httpContextAccessor, env)
        {
            _mediaRepository = mediaRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public GeneralSettings Settings { get; set; }

        public async Task OnGetAsync()
        {
            Settings = await _context.GeneralSettings.FirstOrDefaultAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (string.IsNullOrEmpty(Settings.Id))
            {
                _context.GeneralSettings.Add(Settings);
            }
            else
            {
                _context.Attach(Settings).State = EntityState.Modified;
            }

            await _context.SaveChangesAsync();
            return RedirectToPage("../Home");
        }
    }
}

GymManagment/Pages/Blog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymManagment.Pages
{
    public class BlogModel : PageModel
    {
		private readonly ICMSRepository _cmsRepository;

		public BlogModel(ICMSRepository cmsRepository)
		{
			_cmsRepository = cmsRepository;
		}

		public BlogViewModel Data { get; set; }

		public async Task OnGetAsync(string url)
        {
			Data = await _cmsRepository.GetBlogByUrl(url);
		}
    }
}

GymManagment/Pages/Blogs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GymManagment.Pages
{
    public class BlogsModel : PageModel
    {
		private readonly ICMSRepository _cmsRepository;

		public BlogsModel(ICMSRepository cmsRepository)
		{
			_cmsRepository = cmsRepository;
		}

		public IList<BlogViewModel> Blogs { get; set; }
		public async Task OnGetAsync()
        {
			Blogs = (await _cmsRepository.GetBlogs()).ToList();

			foreach (var item in Blogs)
			{
				item.Content = Regex.Replace(item.Content, @"(?></?\w+)(?>(?:[^>'""]+|'[^']*'|""[^""]*"")*)>", "").Trim();
				item.Content = item.Content.Substring(0, 100);
			}
		}
    }
}

GymManagment/Pages/CMS/AboutUs.cshtml.cs
using AutoMapper;
using GymManagment.Core;
using GymManagment.Core.Models;
using GymManagment.Core.PostModels;
using GymManagment.Repository.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GymManagment.Pages.CMS
{
	public class AboutUsModel : BasePageModel
	{
		private readonly IMediaRepository _mediaRepository;
		private readonly IMapper _mapper;

		public AboutUsModel(ApplicationDbContext context,
			IHttpContextAccessor httpContextAccessor,
			IMediaRepository mediaRepository,
			IMapper mapper,
			IHostingEnvironment env) : base(context, httpContextAccessor, env)
		{
			_mediaRepository = mediaRepository;
			_mapper = mapper;
		}

		[BindProperty]
		public CMSContentViewPostModel Master { get; set; }

		public string ImageURL { get; set; }

		public async Task OnGetAsync()
		{

			var data = await _context.CMSContents.Include(s => s.Media).FirstOrDefaultAsync(m => m.CMSKey == "AboutUs");
			Master = _mapper.Map<CMSContentViewPostModel>(data);
			if (data!=null && data.Media != null)
			{
				ImageURL = data.Media.FileName;
			}
		}


		public async Task<IActionResult> OnPostSaveAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			#region Save Media 
			if (Master.Image != null)
			{
				var mediaResult = await _mediaRepository.SaveMedia(CurrentUserId, Master.Image, "");

				if (mediaResult.IsSuccess)
				{
					Master.MediaId = mediaResult.MediaID;
				}

			}
			#endregion

			var data = _mapper.Map<CMSContentViewPostModel, CMSContent>(Master);
			if (string.IsNullOrEmpty(Master.Id))
			{
				_context.CMSContents.Add(data);
			}
			else
			{
				_context.Attach(data).State = EntityState.Modified;
			}

			await _context.SaveChangesAsync();

			return Redirect("../Home");
		}
	}
}

GymManagment/ViewComponents/BannerViewComponent.cs
using GymManagment.Core;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.ViewComponents
{
    public class BannerViewComponent : ViewComponent
    {
        private readonly ICMSRepository _cmsRepository;
        private readonly ApplicationDbContext _context;

        public BannerViewComponent(ICMSRepository cmsRepository, ApplicationDbContext context)
        {
            _cmsRepository = cmsRepository;
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string key)
        {
            CMSContentSocialViewModel model = new CMSContentSocialViewModel
            {
                CMSContentViewModel = (await _cmsRepository.GetCMSContent(key)).ToList(),
                SocialLinks = _context.GeneralSettings.FirstOrDefault()
            };
            return View(model);
        }
    }
}

GymManagment/ViewComponents/ContactUsViewComponent.cs
using GymManagment.Core;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.ViewComponents
{
	public class ContactUsViewComponent : ViewComponent
	{
		private readonly ApplicationDbContext _context;

		public ContactUsViewComponent(ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var model = await _context.GeneralSettings.FirstOrDefaultAsync();
			return View(model);
		}
	}
}

GymManagment/ViewComponents/GallaryViewComponent.cs
using GymManagment.Core;
using GymManagment.Core.ViewModels;
using GymManagment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.ViewComponents
{
	public class GallaryViewComponent : ViewComponent
	{
		private readonly ICMSRepository _cmsRepository;

		public GallaryViewComponent(ICMSRepository cmsRepository)
		{
			_cmsRepository = cmsRepository;
		}

		public async Task<IViewComponentResult> InvokeAsync(int count=0)
		{
			var items = (await _cmsRepository.GetCMSContent("Gallary", count)).ToList();
			return View(items);
		}
	}
}

GymManagment/ViewComponents/OurValuesViewComponent.cs
using GymManagment.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace GymManagment.ViewComponents
{
    public class OurValuesViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public OurValuesViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            //var model = await _context.CMSContents.Where(i => i.CMSKey == "Mission" || i.CMSKey == "Vision" || i.CMSKey == "CoreValue" || i.CMSKey == "Team").ToListAsync();
            var model = await _context.CMSContents.Where(i => i.CMSKey == "Mission" || i.CMSKey == "Vision").ToListAsync();
            return View(model);
        }
    }
}

GymManagment/Pages/Blog.cshtml
@page "{url}"
@model GymManagment.Pages.BlogModel
@{
	ViewData["Title"] = "Blog";
	Layout = "~/Pages/Shared/_SiteLayout.cshtml";
}


<section class="hero-wrap js-fullheight" style="background-image: url(@Model.Data.FileName);">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<h1 class="mb-3 bread">@Model.Data.Header</h1>
			</div>
		</div>
	</div>
</section>
<section style="padding: 50px 0px;">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 ftco-animate" style="font-size: 18px;color: black;">
				@Html.Raw(Model.Data.Content)
			</div>
			
		</div>
	</div>
</section>

GymManagment/Pages/ContactUs.cshtml
@page
@model GymManagment.Pages.ContactUsModel
@{
    ViewData["Title"] = "Contact Us";
    Layout = "_JitServiceLayout";
}
@await Component.InvokeAsync("ContactUsBanner", new { key = "ContactUsBanner" })
@await Component.InvokeAsync("ContactUs")

GymManagment/Pages/Gallary.cshtml
@page
@model GymManagment.Pages.GallaryModel
@{
	ViewData["Title"] = "Gallary";
	Layout = "~/Pages/Shared/_SiteLayout.cshtml";
}

@await Component.InvokeAsync("Banner", new { key = "GallaryBanner" })

<section class="ftco-gallery">
	<div class="container-wrap">
		<div class="row no-gutters">
			@await Component.InvokeAsync("Gallary")
		</div>
	</div>
</section>

GymManagment/Pages/Index_01.cshtml
@page
@model GymManagment.Pages.IndexModel
@{
    Layout = "_JitLayout";
}
@await Component.InvokeAsync("Banner", new { key = "IndexBanner" })
<section class="ftco-section-services ftco-degree">
    @await Component.InvokeAsync("OurValues")
</section>
<section class="ftco-section bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 heading-section text-center ftco-animate">
                <h3 class="subheading">Set your goal</h3>
                <h2 class="mb-1">Facilities</h2>
            </div>
        </div>
        <div class="row">
            @for (int i = 0; i < Model.Facilities.Count; i++)
            {
                <div class="col-lg-4 d-flex">
                    <div class="coach align-items-stretch">
                        <div class="img" style="background-image: url(@Model.Facilities[i].FileName);"></div>
                        <div class="text bg-white p-4 ftco-animate">
                            <h3><a href="#">@Model.Facilities[i].Text1</a></h3>
                            <p>@Model.Facilities[i].Text2</p>
                            <p></p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="container">
        <div class="row mt-4 justify-content-center ftco-animate">
            <div class="col-md-4 text-center">
                <a href="/Facilities" class="btn-custom py-4">View More Facilities <span class="ion-ios-arrow-down ml-2"></span></a>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section">
    <div class="container-fluid">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <h2 class="mb-1">Workout Programs</h2>
            </div>
        </div>
        <div class="row">
            @for (int i = 0; i < Model.WorkoutPrograms.Count; i++)
            {
                <div class="col-md-6 col-lg-3">
                    <div class="package-program ftco-animate">
                        <a class="img d-flex justify-content-center align-items-center" style="background-image: url(@Model.WorkoutPrograms[i].FileName);">
                        </a>
                        <div class="text mt-3">
                            <h3>@Model.WorkoutPrograms[i].Text1</h3>
                            <p>@Model.WorkoutPrograms[i].Text2</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="container">
        <div class="row mt-4 justify-content-center ftco-animate">
            <div class="col-md-4 text-center">
                <a href="/Program" class="btn-custom py-4">View More Program <span class="ion-ios-arrow-down ml-2"></span></a>
            </div>
        </div>
    </div>
</section>
<section class="ftco-about d-md-flex bg-light">
    <div class="one-half img" style="background-image: url(@Model.AboutUs.FileName);">
        <a href="@Model.AboutUs.Text3" class="icon popup-vimeo d-flex justify-content-center align-items-center">
            <span class="icon-play">
        </a>
        </a>
    </div>
    <div class="one-half ftco-animate">
        <div class="heading-section ftco-animate ">
            <h3 class="subheading">About Club Active</h3>
            <h2 class="mb-5">Welcome<br />to Our Gym</h2>
        </div>
        <div>
            <p>@Html.Raw(@Model.AboutUs.Text1)</p>
        </div>
    </div>
</section>
<section class="ftco-section testimony-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <h3 class="subheading">Testimony</h3>
                <h2 class="mb-1">Successful Stories</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel">
                    @for (int i = 0; i < Model.Testimonials.Count; i++)
                    {
                        <div class="item">
                            <div class="testimony-wrap p-4 pb-5">
                                <div class="text">
                                    <p class="mb-4 pb-1 pl-4 line">@Model.Testimonials[i].Text3</p>
                                    <div class="d-flex align-items-center">
                                        <div class="user-img" style="background-image: url(@Model.Testimonials[i].FileName)">
                                            <span class="quote d-flex align-items-center justify-content-center">
                                                <i class="icon-quote-left"></i>
                                            </span>
                                        </div>
                                        <div class="ml-4">
                                            <p class="name">@Model.Testimonials[i].Text1</p>
                                            <span class="position">@Model.Testimonials[i].Text2</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <h3 class="subheading">Articles</h3>
                <h2 class="mb-1">Recent Blog</h2>
            </div>
        </div>
        <div class="row d-flex">
            @for (int i = 0; i < Model.Blogs.Count; i++)
            {
                <div class="col-md-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="blog-single.html" class="block-20" style="background-image: url(@Model.Blogs[i].FileName);">
                        </a>
                        <div class="text p-4 float-right d-block">
                            <div class="meta">
                                <div><a href="#">@Model.Blogs[i].Date</a></div>
                            </div>
                            <h3 class="heading mt-2"><a href="/Blog/@Model.Blogs[i].URL"> @Model.Blogs[i].Header</a></h3>
                            <p>@Model.Blogs[i].Content</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<section class="ftco-appointment">
    <div class="overlay"></div>
    <div class="container-wrap">
        @await Component.InvokeAsync("ContactUs")
    </div>
</section>
<section class="ftco-gallery">
    <div class="container-wrap">
        <div class="row no-gutters">
            <div class="col-md-3 ftco-animate">
                <div class="gallery ftco-gradient d-flex justify-content-center align-items-center">
                    <div class="row justify-content-center">
                        <div class="col-md-12 heading-section ftco-animate text-center">
                            <h3 class="subheading">Gallery</h3>
                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("Gallary", new { count = 7 })
        </div>
    </div>
</section>

GymManagment/Pages/Settings.cshtml
@page
@model GymManagment.Pages.SettingsModel
@{
    ViewData["Title"] = "Settings";
}

<div class="row">
	<form method="post">

		<div class="col-md-12">

			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Settings.Id" />

			<div class="col-sm-6">
				<div class="form-group">
					<label>Company Name</label>
					<input type="text" asp-for="Settings.CompanyName" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>Address 1</label>
					<input type="text" asp-for="Settings.Address1" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>Address 2</label>
					<input type="text" asp-for="Settings.Address2" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>Address 3</label>
					<input type="text" asp-for="Settings.Address3" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>ContactNo</label>
					<input type="text" asp-for="Settings.ContactNo" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>Website</label>
					<input type="text" asp-for="Settings.Website" class="form-control" />
				</div>
			</div>

			<div class="col-sm-6">
				<div class="form-group">
					<label>Email Address</label>
					<input type="text" asp-for="Settings.EmailAddress" class="form-control" />
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					<label>Invoice Footer Text</label>
					<input type="text" asp-for="Settings.InvoiceFooterText" class="form-control" />
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					<label>Balance Invoice Footer Text</label>
					<input type="text" asp-for="Settings.BalanceInvoiceFooterText" class="form-control" />
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					<label>Balance Invoice Footer Text</label>
					<input type="text" asp-for="Settings.BalanceInvoiceFooterText" class="form-control" />
				</div>
			</div>
			<div class="col-sm-12">
				<div class="form-group">
					<label>About Us</label>
					<input type="text" asp-for="Settings.AboutUs" class="form-control" />
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					<label>Facebook Link</label>
					<input type="text" asp-for="Settings.Facebook" class="form-control" />
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					<label>Twitter Link</label>
					<input type="text" asp-for="Settings.Twitter" class="form-control" />
				</div>
			</div>
			<div class="col-sm-12">
				<div class="form-group">
					<label>Instagram Link</label>
					<input type="text" asp-for="Settings.Instagram" class="form-control" />
				</div>
			</div>

			<div class="form-group">
				<input type="submit" asp-page-handler="Save" value="Save" class="btn btn-primary" />
			</div>

		</div>
	</form>
</div>